type User {
	id: ID!
	token: String
	email: String!
	password: String!
	country: String!
	city: String!
	nickName: String!
	posts: [Post!]
}

type Post {
	id: ID!
	senderId: Int!
	body: String!
	createdAt: Int!
	user: User!
	userId: Int!
}

type Query {
	fetchUserByToken: User!
	fetchUserByEmail(email: String!): User!
}

type Mutation {
	createUser(
		email: String!
		password: String!
		country: String!
		city: String!
		nickName: String!
	): String!
	updateTokenByLogin(email: String!, password: String!): String!
	updatePassword(oldPassword: String!, newPassword: String!, id: Int!): Boolean!
	updateTokenToNull(id: Int!): Boolean!
	createPost(senderId: Int!, body: String!, receiverId: Int!): Boolean!
}
